{{ config(materialized='table') }}

SELECT
    date,
    'Facebook' AS platform,
    campaign_id,
    campaign_name,
    ad_set_id AS ad_group_id,
    ad_set_name AS ad_group_name,
    impressions,
    clicks,
    spend,
    conversions,
    video_views,
    reach,
    engagement_rate,
    frequency,
    NULL AS conversion_value,
    NULL AS quality_score,
    NULL AS search_impression_share,
    NULL AS likes,
    NULL AS shares,
    NULL AS comments,
    NULL AS video_watch_25,
    NULL AS video_watch_50,
    NULL AS video_watch_75,
    NULL AS video_watch_100,
    ROUND(clicks / NULLIF(impressions, 0), 4) AS ctr,
    ROUND(spend / NULLIF(clicks, 0), 2) AS cpc,
    ROUND(spend / NULLIF(impressions, 0) * 1000, 2) AS cpm
FROM {{ source('public', 'FACEBOOK_ADS') }}

UNION ALL

SELECT
    date,
    'Google' AS platform,
    campaign_id,
    campaign_name,
    ad_group_id,
    ad_group_name,
    impressions,
    clicks,
    cost AS spend,
    conversions,
    NULL AS video_views,
    NULL AS reach,
    NULL AS engagement_rate,
    NULL AS frequency,
    conversion_value,
    quality_score,
    search_impression_share,
    NULL AS likes,
    NULL AS shares,
    NULL AS comments,
    NULL AS video_watch_25,
    NULL AS video_watch_50,
    NULL AS video_watch_75,
    NULL AS video_watch_100,
    ROUND(clicks / NULLIF(impressions, 0), 4) AS ctr,
    ROUND(cost / NULLIF(clicks, 0), 2) AS cpc,
    ROUND(cost / NULLIF(impressions, 0) * 1000, 2) AS cpm
FROM {{ source('public', 'GOOGLE_ADS') }}

UNION ALL

SELECT
    date,
    'TikTok' AS platform,
    campaign_id,
    campaign_name,
    adgroup_id AS ad_group_id,
    adgroup_name AS ad_group_name,
    impressions,
    clicks,
    cost AS spend,
    conversions,
    video_views,
    NULL AS reach,
    NULL AS engagement_rate,
    NULL AS frequency,
    NULL AS conversion_value,
    NULL AS quality_score,
    NULL AS search_impression_share,
    likes,
    shares,
    comments,
    video_watch_25,
    video_watch_50,
    video_watch_75,
    video_watch_100,
    ROUND(clicks / NULLIF(impressions, 0), 4) AS ctr,
    ROUND(cost / NULLIF(clicks, 0), 2) AS cpc,
    ROUND(cost / NULLIF(impressions, 0) * 1000, 2) AS cpm
FROM {{ source('public', 'TIKTOK_ADS') }}
